### ISSUE TITLE
endpoints documentation

### ISSUE THREAD

**Issue by phette23** [cca/equella_cli#1]
The endpoints documentation is going to be really long, making the readme unmanageable as features are added. Should it be moved to:

- GitHub wiki?
- a separate markdown doc? (slight preference, don't like tying vital dox into GH platform)

**Comment by lrayshel** [comment]
what is endpoints documentation?

**Comment by phette23** [comment]
It's [the Endpoints section](https://github.com/cca/equella_cli#endpoints) of the readme, which details the options for various API calls. They correspond to types of entries in EQUELLA's database, representing things like users, collections, items.
